irisib_department_list:
    path:     /
    defaults: { _controller: IrisibIntranetBundle:Department:list }

irisib_department_delete:
    path:     /{id}/delete
    defaults: { _controller: "IrisibIntranetBundle:Department:delete" }
    methods:  [POST, DELETE]

irisib_department_add:
    path:     /add
    defaults: { _controller: "IrisibIntranetBundle:Department:create" }
    methods:  [POST, PUT]

irisib_department_update:
    path:     /{id}/update
    defaults: { _controller: "IrisibIntranetBundle:Department:update" }